language: ruby
sudo: false

cache: bundler

bundler_args: --without test --jobs 3 --retry 3

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - gem update bundler

install:
- bundle install --path vendor/bundle

script: bundle exec rake

rvm:
- 2.0.0
- 2.1.5
- 2.2.2
- 2.2.3
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false
