require 'rubygems'
require 'bundler'
require 'bundler/setup'
require 'celluloid/io'
require 'reel'
require 'celluloid/websocket/client'
require 'active_support/all'
require 'json'
require 'celluloid_pubsub/base_actor'
Gem.find_files('celluloid_pubsub/**/*.rb').each { |path| require path }
